/**************************************************************************
* BORRA LAS TABLAS SI YA EXISTEN
***************************************************************************/

DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS CARGOS;
DROP TABLE IF EXISTS DEPARTAMENTOS;

/**************************************************************************
* CREACION DE LAS TABLAS
***************************************************************************/

CREATE TABLE DEPARTAMENTOS
(
	COD_DEPART INT(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE)),
	LOCALIZACION VARCHAR(20) NOT NULL CHECK (LOCALIZACION IN('ELORRIETA', 'ERREKAMARI'))
);

CREATE TABLE CARGOS
(
	COD_CARGO INT(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE))
);

CREATE TABLE EMPLEADOS
(
	COD_EMPLE INT(3) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL CHECK (NOMBRE = UPPER(NOMBRE)),
	APELLIDOS VARCHAR(50) NOT NULL CHECK (APELLIDOS = UPPER(APELLIDOS)),
	SUELDO FLOAT(6) NOT NULL,
	COD_DEPART INT(3) NOT NULL,
	COD_CARGO INT(3) NOT NULL,
	COD_JEFE INT(3),
	ES_JEFE BOOLEAN NOT NULL,
	FECHA_ALTA DATETIME NOT NULL,
	FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTOS (COD_DEPART),
	FOREIGN KEY (COD_CARGO) REFERENCES CARGOS (COD_CARGO),
	FOREIGN KEY (COD_JEFE) REFERENCES EMPLEADOS (COD_EMPLE)
);